### PR TITLE
[DO NOT MERGE JUST YET] WIP - Rewrite

### PR DESCRIPTION
**Pull request by motss**
## TODO

- [x] ~~Upgrading to **Polymer v2.0**~~
- [ ] Upgrading to Polymer v3.0 that comes with [lit-html](https://github.com/PolymerLabs/lit-html)
- [ ] Major version bump to **v3.0.0**

---
This change is [Reviewable](https://reviewable.io/reviews/motss/app-datepicker/76)

### CODE REVIEW

**Comment by santanubasu** [comment]
Would love to get a P2 version of this component, if you have something that is testable with polymer 2 RC's I would be happy to pull it down and try it out.  In general, what is the anticipated timeline to get basic date picking functionality working for P2?

**Comment by motss** [comment]
@santanubasu Thank you for your support. I planned to release it as soon as possible right after Polymer 2.0 goes stable for 1 or 2 weeks for better compatibility and stability. Please look forward to it. Once again thank you. 😏

**Comment by yorrd** [comment]
@motss just wondering, is the 2.0-preview branch supposed to work at the moment? I'm using it and the `<app-datepicker/>` just shows up empty

**Comment by motss** [comment]
@yorrd Still working in progress.

**Comment by stephanieder** [comment]
Hello ! What is the state of compatibility to Polymer 2 please ? Thank you ! :)

**Comment by motss** [comment]
@stephanieder This PR aims to rewrite the whole element in ESNext (beyond ES7+) and web technologies that are not widely supported on all browsers. If you're looking to use this element with Polymer 2.x, please note that this element has become a Hybrid Polymer Element that is compatible with both Polymer 1.x and Polymer 2.x. Should you encounter any issue, feel free to open issues!~ 😄

**Comment by motss** [comment]
After the announcement of Polymer 3.0 and the efforts on publishing better Web Components with Yarn or NPM, Polymer users do care about SSR Web Components with official support from Google.

Therefore, I decided to put a hold on this PR until the Polymer 3.0 goes stable.

**Pull request closed without merging**
