### PR TITLE
PR for bug 90 (2)

### LINKED ISSUE #90: PR #89 must be reviewed to handle min and max dates
It seems we also need to change _isDisableDays function to do logic with UTC instead with local TZ.

### PR DESCRIPTION
**Pull request by userquin**
Fixes #90

see commit comments for changes

---
This change is [Reviewable](https://reviewable.io/reviews/motss/app-datepicker/92)

### CODE REVIEW

**Comment by userquin** [comment]
I have to modify:
```javascript
_isDisableDays: function (_index, _firstDayOfWeek, _minDate, _maxDate, _item) {
```
to
```javascript
_isDisableDays: function (_index, _firstDayOfWeek, _minDateObj, _maxDateObj, _item) {
          if (_minDateObj) {
            _isLessThanMinDate = _currentDate < _minDateObj;
           }
          if (_maxDateObj) {
            _isMoreThanMaxDate = _currentDate > _maxDateObj;
          }
}
```
also
```html
 <div class$="each-days-of-month[[_isToday(item.index, _activeYear, _activeMonth)]][[_isEmptyDate(item.index)]][[_isChosenDaysOfMonth(item.index, _selectedYear, _selectedMonth, _selectedDate)]][[_isDisableDays(index, firstDayOfWeek, minDate, maxDate, item.index, _shiftedDisableDays.*, disableDates.*)]]" index="[[index]]" date="[[item.index]]" tabindex$="[[_shouldTabIndex(index, firstDayOfWeek, minDate, maxDate, item.index, _shiftedDisableDays.*, disableDates.*)]]" aria-disabled$="[[_shouldAriaDisabled(index, firstDayOfWeek, minDate, maxDate, item.index, _shiftedDisableDays.*, disableDates.*)]]" aria-label$=[[item.index]]>
```
with this one
```html
 <div class$="each-days-of-month[[_isToday(item.index, _activeYear, _activeMonth)]][[_isEmptyDate(item.index)]][[_isChosenDaysOfMonth(item.index, _selectedYear, _selectedMonth, _selectedDate)]][[_isDisableDays(index, firstDayOfWeek, minDate, maxDate, item.index, _shiftedDisableDays.*, disableDates.*)]]" index="[[index]]" date="[[item.index]]" tabindex$="[[_shouldTabIndex(index, firstDayOfWeek, minDateObj, maxDateObj, item.index, _shiftedDisableDays.*, disableDates.*)]]" aria-disabled$="[[_shouldAriaDisabled(index, firstDayOfWeek, minDate, maxDate, item.index, _shiftedDisableDays.*, disableDates.*)]]" aria-label$=[[item.index]]>
```

**Comment by userquin** [comment]
I have it working and with no breaking changes, that is, min, max and disable dates can be any dateString Date constructor accepts (like your original): app-datepicker will convert properly to client TZ and do the logic. The demo page will remain with ISO date format on min, max and disable dates I also include a remark in the documentation.

I'm finishing some tests with different timezones... As soon as possible I'll make the push with the changes.

**Comment by userquin** [comment]
I think you should add to your travis configuration file 2 new tests, adding under env directive 3 TZ entries, for example (I have never tested this):

```yml
env:
  - TZ=Asia/Singapore
  - TZ=Europe/Madrid
  - TZ=America/Los_Angeles
```

You can read more about this:

https://docs.travis-ci.com/user/environment-variables/#Defining-Multiple-Variables-per-Item

**Comment by motss** [comment]
@userquin Isn't this one can be set directly on the `.travis.yml` file?

**Comment by userquin** [comment]
I think you can, but not tested...
Take a look at:
https://docs.travis-ci.com/user/languages/javascript-with-nodejs/
For Ember configures env and matrix env...

**Comment by userquin** [comment]
Sorry, I did not understand you, yes add it at the end of the .travis.yml

**Comment by userquin** [comment]
If it works, we can add some failing tests for known dates, for example for Madrid using october and september 1995 and for the rest we need to find suitable failing scenarios, so the tests will check all works as expected...

**Comment by motss** [comment]
@userquin From the example you provided, those can be set in the `.travis.yml` https://github.com/motss/app-datepicker/blob/master/.travis.yml.

**Comment by userquin** [comment]
Are you reviewing the push? 
I have found an errata in _isDisableDays function:
```javascript
1128: if (!_isDisableDates && this._isNumber(_item)) {
``` 
muts be
```javascript
1128: if (!_isDisableDays && this._isNumber(_item)) {
``` 
and another in _computeDaysOfWeek function:
```javascript
1168: var _firstDayOfWeek = _firstDayOfWeek > 0 && _firstDayOfWeek < 7 ? _firstDayOfWeek : 0;
1187: var _sliced = _dow.slice(_firstDayOfWeek);
1188: var _rest = _dow.slice(0, _firstDayOfWeek);
``` 
muts be (or reassign the _firstDayOfWeek to the expression)
```javascript
1168: var __firstDayOfWeek = _firstDayOfWeek > 0 && _firstDayOfWeek < 7 ? _firstDayOfWeek : 0;
1187: var _sliced = _dow.slice(__firstDayOfWeek);
1188: var _rest = _dow.slice(0, __firstDayOfWeek);
```

**Comment by motss** [comment]
what's wrong here.

**Comment by userquin** [comment]
the first one is not wrong is to avoid evaluate max, min or find in the list if already disabled by week day

last code has two vars with the same name, first method parameter and 
1168: var _firstDayOfWeek = _firstDayOfWeek > 0 && _firstDayOfWeek < 7 ? _firstDayOfWeek : 0;

**Comment by motss** [comment]
Closing this in favor of `v4`. Highly recommend using `v4` even if you are using `polymer`.

Thank you for the support.

**Pull request closed without merging**
