### PR TITLE
internally update readOnly property date

### PR DESCRIPTION
**Pull request by HaykoKoryun**
update `readOnly` property `date` so the change can be observed from host

### CODE REVIEW

**Comment by motss** [comment]
@HaykoKoryun May I know what kind of issue this tries to resolve?

**Comment by HaykoKoryun** [comment]
Hey @motss, in the documentation it states that the `date` property `notifies` which is true. However you currently don't actually update the `date` property when a user selects a date from the picker, or at least I couldn't fine an event to bind to get the date as it was being selected.

With this addition, (which I may have inserted in a less than ideal point in your code) the `date` property gets updated on every date select so binding to the event `date-changed` on `app-datepicker` allows us to get notified when the user selects a date.

**Comment by motss** [comment]
@HaykoKoryun 
I think I get the issue you're facing.

The `date` property will not get updated when a date is selected. Why?

It is because `date` will only be updated or notified of the latest selected date when the user asks to do so. The idea behind this is that the datepickers are usually used with overlays/ dialogs and there are usually buttons inside to confirm the selected date. Let's imagine this patch actually updates the `date` property on every selected date changed. The user might confuse as they don't even pressed the OK button to confirm the date changed when they can actually close the datepicker or even click on the cancel button. In that case, an element that binds to the `date` property should not be updated.

However, how about using the datepicker without even using an overlay/ dialog just a plain datepicker on the document and the `date` needs to be updated on selected date changed assuming buttons are nowhere to update the `date` property? To deal with this issue, there is already a public method `enforceDateChange` for that purpose. The method will internally update the `date` based on the selected date by the user.

Hope this helps.

**Comment by HaykoKoryun** [comment]
Thanks @motss, must have missed that property when looking at the docs. Thanks for the tip.

**Comment by HaykoKoryun** [comment]
Just tried using `enforceDateChange` however that doesn't actually solve the issue since the function only updates the `date` property at that moment but not automatically in the future.

I think a better approach then would be to add a property to `app-datepicker` which allows the user to toggle the behaviour to auto-update the `date` property.

**Comment by motss** [comment]
@HaykoKoryun Do you mind file a PR to fix that?

**Comment by HaykoKoryun** [comment]
I just changed the behaviour so now a `boolean` property `autoUpdateDate` controls whether the `date` property gets auto-updated (and the default is false so it doesn't break current behaviour).

**Comment by motss** [comment]
@HaykoKoryun Thanks for your contribution. However, I found that calling the public method `enforceDateChange` is much preferable as it will take account for both short and long date.

```
  ...
  if (this.autoUpdateDate) {
    // This method will check if the property `showLongDate` is truthy, then compute the `date` into the correct format.
    this.enforceDateChange();
  }
  ...
```

**Pull request closed without merging**
